name: Discover Tests 

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Run scraper in container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kayperooo --password-stdin
          docker run --rm \
            -e GMK=${{ secrets.GMK }} \
            -e SU=${{ secrets.SU }} \
            -e SK=${{ secrets.SK }} \
            -e DBP=${{ secrets.DBP }} \
            -e DWU=${{ secrets.DWU }} \
            ghcr.io/kayperooo/scraper:latest \
            python -m src.scripts.run_discover > /dev/null 2>&1
